=== AdvancedMUSicExplorer/AMUSE/amuse/tools/jAudio/jAudio.dtd
<!ELEMENT batchFile (batch+)>
<!ELEMENT batch (fileSet,settings,destination+)>
<!ATTLIST batch ID CDATA "" >
<!ELEMENT fileSet (file+)>
<!ELEMENT file (#PCDATA)>
<!ELEMENT settings (windowSize,windowOverlap,samplingRate,normalise,perWindowStats,overallStats,outputType,feature+)>
<!ELEMENT windowSize (#PCDATA)>
<!ELEMENT windowOverlap (#PCDATA)>
<!ELEMENT samplingRate (#PCDATA)>
<!ELEMENT normalise (#PCDATA)>
<!ELEMENT perWindowStats (#PCDATA)>
<!ELEMENT overallStats (#PCDATA)>
<!ELEMENT outputType (#PCDATA)>
<!ELEMENT amuseEnableFeature (feature)>
<!ELEMENT feature (name,active,attribute*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT active (#PCDATA)>
<!ELEMENT attribute (#PCDATA)>
<!ELEMENT destination (#PCDATA)>

=== AdvancedMUSicExplorer/AMUSE/amuse/tools/jAudio/jAudioBaseModified512.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE batchFile SYSTEM "jAudio.dtd">
<batchFile>
	<batch ID="test">
		<fileSet>
			<file>/Users/aylinozek/Desktop/RWTH/hiwiamuse/AMUSE/amuse/config/node/extractor/input/task_167/1/704231__ztidlen__rockaisound-rockgenre-16.wav</file>
		</fileSet>
		<settings>
			<windowSize>512</windowSize>
			<windowOverlap>0.0</windowOverlap>
			<samplingRate>22050.0</samplingRate>
			<normalise>false</normalise>
			<perWindowStats>true</perWindowStats>
			<overallStats>false</overallStats>
			<outputType>ARFF</outputType>
			<feature>
				<name>Derivative of Running Mean of Strongest Beat</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Beat Histogram Bin Labels</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Standard Deviation of Partial Based Spectral Flux</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Derivative of Running Mean of Zero Crossings</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Standard Deviation of Strongest Frequency Via FFT Maximum</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Derivative of Running Mean of Peak Based Spectral Smoothness</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Strongest Frequency Via FFT Maximum</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Running Mean of Method of Moments</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Standard Deviation of Root Mean Square</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Strongest Frequency Via Spectral Centroid</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Derivative of Running Mean of Strongest Frequency Via FFT Maximum</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Derivative of Spectral Variability</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Derivative of Standard Deviation of Compactness</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Derivative of Running Mean of Spectral Centroid</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Derivative of Standard Deviation of Strength Of Strongest Beat</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>LPC</name>
				<active>false</active>
				<attribute>0.0</attribute>
				<attribute>10</attribute>
			</feature>
			<feature>
				<name>Derivative of Running Mean of MFCC</name>
				<active>false</active>
				<attribute>13</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Derivative of Strongest Frequency Via Spectral Centroid</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Derivative of Standard Deviation of Strongest Frequency Via Spectral Centroid</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>MFCC</name>
				<active>true</active>
				<attribute>13</attribute>
			</feature>
			<feature>
				<name>Derivative of Spectral Flux</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Derivative of Standard Deviation of Method of Moments</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Partial Based Spectral Centroid</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Derivative of Running Mean of Fraction Of Low Energy Windows</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Derivative of Relative Difference Function</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Running Mean of Spectral Rolloff Point</name>
				<active>false</active>
				<attribute>0.85</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Derivative of Standard Deviation of Area Method of Moments</name>
				<active>false</active>
				<attribute>10</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Strongest Beat</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Derivative of Running Mean of Strongest Frequency Via Spectral Centroid</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Running Mean of Relative Difference Function</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Running Mean of LPC</name>
				<active>false</active>
				<attribute>0.0</attribute>
				<attribute>10</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Derivative of Compactness</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Standard Deviation of Spectral Centroid</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Beat Sum</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Standard Deviation of Spectral Variability</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Derivative of Standard Deviation of Zero Crossings</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Derivative of Running Mean of Strength Of Strongest Beat</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Derivative of Fraction Of Low Energy Windows</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Running Mean of Zero Crossings</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Derivative of Peak Based Spectral Smoothness</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Standard Deviation of Spectral Rolloff Point</name>
				<active>false</active>
				<attribute>0.85</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Standard Deviation of Relative Difference Function</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Derivative of Running Mean of Method of Moments</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Derivative of Root Mean Square</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Derivative of Standard Deviation of Peak Based Spectral Smoothness</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Running Mean of Strongest Frequency Via FFT Maximum</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Derivative of Standard Deviation of Partial Based Spectral Centroid</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Derivative of Zero Crossings</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Spectral Variability</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Peak Based Spectral Smoothness</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Running Mean of Partial Based Spectral Flux</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Derivative of Strongest Frequency Via Zero Crossings</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Derivative of Running Mean of Spectral Variability</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Running Mean of Strength Of Strongest Beat</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Derivative of Spectral Rolloff Point</name>
				<active>false</active>
				<attribute>0.85</attribute>
			</feature>
			<feature>
				<name>Running Mean of Spectral Centroid</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Derivative of Spectral Centroid</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Derivative of Standard Deviation of Root Mean Square</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Spectral Centroid</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Standard Deviation of LPC</name>
				<active>false</active>
				<attribute>0.0</attribute>
				<attribute>10</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Derivative of Running Mean of Root Mean Square</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Running Mean of Spectral Variability</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Derivative of Strongest Beat</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Derivative of Running Mean of Area Method of Moments</name>
				<active>false</active>
				<attribute>10</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Magnitude Spectrum</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Standard Deviation of Compactness</name>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<name>Power Spectrum</name>
				<active>false</active>
			</feature>
			<feature>
				<name>Area Method of Moments</name>
				<active>false</active>
				<attribute>10</attribute>
			</feature>
			<feature>
				<name>Derivative of Running Mean of Relative Difference Function</name>
				<active>false</active>
